# Generated by "cinit vm"
SOURCES=$(wildcard src/*.cpp)
OBJECTS=$(SOURCES:.cpp=.o)
CXXFLAGS=-Wall -Wextra -Werror -Wno-unused-function -std=gnu++17 -I./include/
EXECUTABLE=synacor-vm

HAS_CCACHE := $(shell command -v ccache 2> /dev/null)
ifdef HAS_CCACHE
    CXX:=ccache $(CXX)
endif

all: $(EXECUTABLE)

$(EXECUTABLE) : $(OBJECTS)
	$(CXX) -o $@ $^ $(LIBS) $(CXXFLAGS)

run:
	./$(EXECUTABLE) ./challenge.bin

clean:
	$(RM) $(EXECUTABLE)
	$(RM) $(OBJECTS)

.PHONY: run clean
